### PR TITLE
Support defining /root/.k5login and /root/.k5users

### LINKED ISSUE #8: Also manage /root/.k5login and /root/.k5users?
Would you be willing to add support for managing `/root/.k5login` and `/root/.k5users` to this module?

### PR DESCRIPTION
**Pull request by treydock**
Fixes #8

### CODE REVIEW

**Comment by jcpunk** [comment]
Might it be worth adding a comment to the files to indicate they are managed by puppet (and how to disable it)?

**Comment by treydock** [comment]
Disable what?

**Comment by treydock** [comment]
Added comments to those files to indicate they are managed by Puppet.  Quick google says Kerberos treat comments like principles so sort of works I guess.  I don't actively deploy Kerberos so not sure what comment syntax rules are for these files.

**Comment by jcpunk** [comment]
If the comments could be updated to something like `# File managed by Puppet (root::manage_kerberos = true), DO NOT EDIT'` that would be helpful to let people know quickly which class is managing the file and what settings to toggle to disable it.

As for the comment character `#` is indeed correct.

**Comment by treydock** [comment]
This is released as v4.4.0, the Forge release will occur once the build pipeline finishes

**Pull request merged**
